[package]
name = "text21/rewind"
version = "1.2.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["docs/**", ".github/**", "*.md"]

[dependencies]
trove = "sleitnick/trove@1.8.0"
signal = "sleitnick/signal@2.0.3"
promise = "evaera/promise@4.0.0"
table-util = "sleitnick/table-util@1.2.1"
t = "osyrisrblx/t@3.1.1"

[dev-dependencies]
iris = "sirmallard/iris@2.5.0"
testez = "roblox/testez@0.4.1"
